# Generated by Django 2.0.5 on 2018-05-08 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonereviews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phonereviews',
            name='updated_at',
        ),
    ]
